# backend/presenter_router.py
# ──────────────────────────────────────────────────────────────
# Unified presenter — formats ANY structured data into the
# envelope format that the frontend RenderBlock component expects.
#
# KEY DESIGN:
#   - Tables are built LOCALLY by _flatten_top_level() — NO LLM.
#   - Summaries are generated by the shared llm.py gateway
#     (same provider/model the rest of the app uses).
#   - PII is stripped from data BEFORE it reaches the LLM.
#   - The frontend envelope contains the ORIGINAL (full) data.
# ──────────────────────────────────────────────────────────────
from __future__ import annotations
import os, json, threading, re, io, base64
from urllib.parse import quote
from typing import Any, Callable, Dict, List, Tuple, Optional
from fastapi import APIRouter
from pydantic import BaseModel
from dotenv import load_dotenv

from utils.llm import chat as llm_chat
from utils.html_sanitizer import clean_html
from utils.llm_config import LLM_PROVIDER, LLM_MODEL
from utils.pii_filter import sanitize_for_llm, PII_FILTER_ENABLED
from personality import compile_personality_block, get_preset

# ===================== Setup (.env) =====================
load_dotenv(dotenv_path=os.path.join(os.getcwd(), ".env"))

# Global feature flags / config
PRESENTER_USE_LLM_SCHEMA_HINTS = os.getenv("PRESENTER_USE_LLM_SCHEMA_HINTS", "false").lower() == "true"
PRESENTER_TELEMETRY_SINK = os.getenv("PRESENTER_TELEMETRY_SINK", "console").lower()   # console | off

router = APIRouter(prefix="/api", tags=["presenter"])

UI_PREVIEW_ROWS = 50
Scalar = (str, int, float, bool, type(None))

# Generic wrapper keys that get priority when two keys tie on array length.
# These are common "generic" wrapper names used across many APIs/ERPs.
# Domain-specific keys (customers, jobs, invoices, quotes, etc.) are auto-detected
# by _find_data_array() — no need to register them here.
_GENERIC_DATA_KEYS = frozenset(("data", "results", "items", "value", "records", "rows"))

# Keys that are clearly metadata, not the main data array — skip them during auto-detection.
_META_KEYS = frozenset((
    "success", "error", "errors", "message", "status", "code",
    "total", "total_fetched", "total_count", "count",
    "page", "pages", "pages_fetched", "page_size", "pageSize",
    "next", "previous", "cursor", "has_more",
    "formatted", "tool", "metadata", "meta", "warnings",
))


def _find_data_array(payload: Dict[str, Any]) -> Optional[str]:
    """Auto-detect which key in a dict-wrapper holds the main data array.

    Strategy:
      1. Skip keys that are known metadata (_META_KEYS).
      2. Among remaining keys whose value is a non-empty list, pick the one
         with the most items.  On ties, prefer _GENERIC_DATA_KEYS.
      3. If there's only one list-valued key (ignoring metadata), use it
         regardless of length — even a 1-element list is valid data.

    Returns the key name, or None if no suitable array is found.
    """
    candidates: List[Tuple[str, int]] = []   # (key, length)
    for k, v in payload.items():
        if k in _META_KEYS:
            continue
        if isinstance(v, list) and v:
            candidates.append((k, len(v)))

    if not candidates:
        return None

    # Single candidate — no ambiguity
    if len(candidates) == 1:
        return candidates[0][0]

    # Multiple candidates — pick longest; break ties by generic-key priority
    candidates.sort(key=lambda x: (x[1], x[0] in _GENERIC_DATA_KEYS), reverse=True)
    return candidates[0][0]

# ===================== Telemetry (in-memory) =====================
_stats_lock = threading.Lock()
_stats = {
    "hints_requested": 0,
    "hints_applied": 0,
    "hints_ignored": 0,
    "dropped_keys_total": 0,
    "columns_built_total": 0
}

def _stats_inc(key: str, amt: int = 1):
    with _stats_lock:
        _stats[key] = _stats.get(key, 0) + amt

def _telemetry_log(event: str, data: Dict[str, Any]):
    if PRESENTER_TELEMETRY_SINK == "console":
        try:
            print(f"[presenter][{event}] {json.dumps(data, ensure_ascii=False)}")
        except Exception:
            pass

@router.get("/presenter/stats")
def presenter_stats():
    with _stats_lock:
        return dict(_stats)

@router.post("/presenter/stats/reset")
def presenter_stats_reset():
    with _stats_lock:
        for k in _stats.keys():
            _stats[k] = 0
    return {"ok": True}

# ===================== Models =====================
class PresentRequest(BaseModel):
    question: str
    payload: Any
    hints: Optional[Dict[str, Any]] = None  # { llm_schema_hints?: bool, allow_llm?: bool }
    llm_fn: Optional[Any] = None  # Per-org LLM callable — passed from chat.py's _effective_llm_chat

    class Config:
        arbitrary_types_allowed = True

class PresentResponse(BaseModel):
    envelope: Dict[str, Any]
    telemetry: Dict[str, Any]

# ===================== CSV helper =====================
def _csv_blob_full(rows: List[Dict[str, Any]]) -> str:
    if not rows:
        return "data:text/csv;charset=utf-8,"
    cols: List[str] = []
    seen = set()
    for r in rows:
        if isinstance(r, dict):
            for k in r.keys():
                if k not in seen:
                    seen.add(k); cols.append(k)

    def esc(v: Any) -> str:
        s = "" if v is None else str(v)
        if any(c in s for c in [",", '"', "\n"]):
            s = '"' + s.replace('"','""') + '"'
        return s

    header = ",".join(cols)
    body = "\n".join(",".join(esc(r.get(c)) for c in cols) for r in rows)
    csv_text = header + "\n" + body
    return "data:text/csv;charset=utf-8," + quote(csv_text, safe=",")

# ===================== Excel helper =====================
def _xlsx_blob(rows: List[Dict[str, Any]]) -> str:
    """Build a base64 data-URL for an .xlsx file from a list of row dicts."""
    from openpyxl import Workbook
    from openpyxl.styles import Font, PatternFill, Alignment, Border, Side

    wb = Workbook()
    ws = wb.active
    ws.title = "Export"

    if not rows:
        buf = io.BytesIO()
        wb.save(buf)
        b64 = base64.b64encode(buf.getvalue()).decode()
        return f"data:application/vnd.openxmlformats-officedocument.spreadsheetml.sheet;base64,{b64}"

    # Collect column keys in insertion order
    cols: List[str] = []
    seen = set()
    for r in rows:
        if isinstance(r, dict):
            for k in r.keys():
                if k not in seen:
                    seen.add(k); cols.append(k)

    # Header row styling
    header_font = Font(bold=True, color="FFFFFF", size=11)
    header_fill = PatternFill(start_color="4472C4", end_color="4472C4", fill_type="solid")
    header_align = Alignment(horizontal="center", vertical="center")
    thin_border = Border(
        bottom=Side(style="thin", color="B4C6E7"),
    )

    for ci, col_name in enumerate(cols, 1):
        cell = ws.cell(row=1, column=ci, value=_humanize_label(col_name))
        cell.font = header_font
        cell.fill = header_fill
        cell.alignment = header_align

    # Data rows
    alt_fill = PatternFill(start_color="D9E2F3", end_color="D9E2F3", fill_type="solid")
    for ri, row in enumerate(rows, 2):
        for ci, col_name in enumerate(cols, 1):
            cell = ws.cell(row=ri, column=ci, value=row.get(col_name, ""))
            cell.border = thin_border
            if ri % 2 == 0:
                cell.fill = alt_fill

    # Auto-fit column widths (approximate)
    for ci, col_name in enumerate(cols, 1):
        max_len = len(_humanize_label(col_name))
        for ri in range(2, min(len(rows) + 2, 52)):  # sample first 50 rows
            val = str(ws.cell(row=ri, column=ci).value or "")
            max_len = max(max_len, len(val))
        ws.column_dimensions[ws.cell(row=1, column=ci).column_letter].width = min(max_len + 3, 50)

    buf = io.BytesIO()
    wb.save(buf)
    b64 = base64.b64encode(buf.getvalue()).decode()
    return f"data:application/vnd.openxmlformats-officedocument.spreadsheetml.sheet;base64,{b64}"

# ===================== Flattening (deep — all nested data merged) =====
# ALL nested data (objects, arrays of objects) is flattened into the
# main row with prefixed column names.  No sub-tables are created.
# This keeps every field from the API response visible in one table.
# =====================================================================
def _join(prefix: str, key: str) -> str:
    return key if not prefix else f"{prefix}_{key}"


def _deep_flatten_dict(obj: Dict[str, Any], prefix: str) -> Dict[str, Any]:
    """Recursively flatten a dict.  Nested dicts get prefixed keys.
    Lists of dicts get their values joined per-field."""
    out: Dict[str, Any] = {}
    for k, v in obj.items():
        key = _join(prefix, k)
        if isinstance(v, dict):
            out.update(_deep_flatten_dict(v, key))
        elif isinstance(v, list):
            out.update(_deep_flatten_list(v, key))
        else:
            out[key] = clean_html(v) if isinstance(v, str) else v
    return out


def _deep_flatten_list(lst: list, key: str) -> Dict[str, Any]:
    """Flatten a list value into columns.
    - Empty list        → key: ""
    - Scalars           → key: comma-joined string
    - List of dicts     → flatten each item, then join values per column
    """
    out: Dict[str, Any] = {}
    if not lst:
        out[key] = ""
        return out
    # All scalars — join
    if all(isinstance(x, Scalar) for x in lst):
        out[key] = ", ".join(str(x) for x in lst)
        return out
    # All dicts — flatten each, then merge per-field
    if all(isinstance(x, dict) for x in lst):
        flat_items = [_deep_flatten_dict(item, key) for item in lst]
        # Collect all keys in order
        all_keys: list[str] = []
        seen: set[str] = set()
        for fi in flat_items:
            for fk in fi.keys():
                if fk not in seen:
                    seen.add(fk)
                    all_keys.append(fk)
        # For single-item lists, use values directly; for multi-item, join
        if len(flat_items) == 1:
            out.update(flat_items[0])
        else:
            for fk in all_keys:
                vals = [fi.get(fk) for fi in flat_items]
                # Filter None and join as comma-separated
                str_vals = [str(v) for v in vals if v is not None]
                out[fk] = ", ".join(str_vals) if str_vals else ""
        return out
    # Mixed types — JSON dump
    out[key] = json.dumps(lst, ensure_ascii=False)
    return out


def _flatten_row(item: Any) -> Tuple[Dict[str, Any], Dict[str, List]]:
    """Return (flat_row, empty_nested_dict).
    All nested data is now flattened into the main row — no sub-tables."""
    nested: Dict[str, List] = {}   # always empty now
    if isinstance(item, dict):
        return _deep_flatten_dict(item, ""), nested
    if isinstance(item, list):
        return _deep_flatten_list(item, "value"), nested
    return {"value": item}, nested


def _flatten_top_level(payload: Any) -> Tuple[List[Dict[str, Any]], List[str], Dict[str, List]]:
    """Returns (rows, columns, all_nested).
    *all_nested* aggregates every nested array across all rows so the
    envelope builder can create sub-table blocks for them."""
    rows: List[Dict[str, Any]] = []
    all_nested: Dict[str, List] = {}

    def _add(item):
        flat, nested = _flatten_row(item)
        rows.append(flat)
        for k, v in nested.items():
            all_nested.setdefault(k, []).extend(v)

    if isinstance(payload, list):
        for it in payload:
            _add(it)
    elif isinstance(payload, dict):
        # Auto-detect which key holds the main data array (ERP-agnostic)
        data_key = _find_data_array(payload)
        if data_key is not None:
            for it in payload[data_key]:
                _add(it)
        else:
            _add(payload)
    else:
        _add(payload)

    cols: List[str] = []
    seen = set()
    for r in rows:
        for k in r.keys():
            if k not in seen:
                seen.add(k); cols.append(k)
    return rows, cols, all_nested

# ===================== LLM helpers =====================
def _first_json_obj(text: str) -> Optional[Dict[str, Any]]:
    m = re.search(r"\{[\s\S]*\}", text)
    if not m:
        return None
    try:
        return json.loads(m.group(0))
    except Exception:
        return None


def _llm_json(
    system: str,
    user: str,
    temperature: float = 0.0,
    llm_fn: Optional[Callable] = None,
) -> Optional[Dict[str, Any]]:
    """
    Send system + user prompt to the LLM and parse a JSON object.
    Uses per-org llm_fn when provided, falls back to global llm_chat.
    """
    fn = llm_fn or llm_chat
    try:
        messages = [
            {"role": "system", "content": system},
            {"role": "user", "content": user},
        ]
        txt = fn(
            messages,
            response_format={"type": "json_object"},
            temperature=temperature,
            sanitize=False,   # data is already sanitized by callers
        )
        txt = (txt or "").strip()
        print(f"[presenter][llm][raw_response]", repr(txt[:500]))

        # Try direct JSON parse
        try:
            data = json.loads(txt)
            if isinstance(data, dict):
                return data
        except json.JSONDecodeError as e:
            print("[presenter][llm][parse][json_error]", str(e))

            # Try cleaning markdown fences
            try:
                cleaned = re.sub(r'^```(?:json)?\s*|\s*```$', '', txt, flags=re.MULTILINE).strip()
                data = json.loads(cleaned)
                if isinstance(data, dict):
                    print("[presenter][llm][parse] Succeeded after cleaning markdown")
                    return data
            except json.JSONDecodeError:
                pass

            # Final fallback: extract first JSON object
            data = _first_json_obj(txt)
            if data:
                print("[presenter][llm][parse] Succeeded with regex extraction")
                return data

        if data is None:
            print("[presenter][llm][parse] No valid JSON object found")
        return data

    except Exception as e:
        print("[presenter][llm][error]", str(e))
        return None


# ===================== LLM: summary + schema hints =====================
_PERSONALITY_SUMMARY = compile_personality_block("summary")
_PERSONALITY_TEMP = get_preset().get("temperature_narrative", 0.15)

_DATA_MASKING_SECTION = """
DATA MASKING (IMPORTANT):
- Financial values in the payload are MASKED for data protection.
- Instead of raw dollar amounts you will see relative metrics:
  - "ActualVsEstimate": "26.6%" — means actual is 26.6% of estimate
  - "ActualVsEstimate": "negative" — means actual is NEGATIVE (a loss/deficit)
  - "BudgetStatus": "loss" — actual value is NEGATIVE. This is CRITICAL for profitability:
    if GrossProfitLoss or NetProfitLoss shows "loss", that cost centre is UNPROFITABLE.
  - "BudgetStatus": "under_estimate" / "over_estimate" / "well_under_estimate" / "well_over_estimate" / "on_estimate" / "no_activity"
  - "positive" / "negative" — indicates the sign of a value without the amount
- Use these relative indicators to describe trends and comparisons.
- PAY SPECIAL ATTENTION to "loss" status:
  - GrossProfitLoss with "loss" = the cost centre is making a LOSS
  - GrossMargin with "negative" = negative margin = UNPROFITABLE
  - Do NOT claim something is profitable if its profit/margin shows "loss" or "negative"
- NEVER invent or guess actual dollar amounts. Use language like:
  - "Materials are well under estimate (27% of estimate)"
  - "Labor costs are tracking over estimate"
  - "Gross margin is positive"
  - "Cost centre X is running at a LOSS"
- Do NOT say "the exact figures are masked" or mention masking to the user.
  Simply describe the data using the relative terms provided.
"""

_REAL_DATA_SECTION = """
FINANCIAL DATA (IMPORTANT):
- The payload contains REAL dollar amounts. Use the EXACT values from the data.
- When the payload includes a "_financial_summary" object on each record, ALWAYS
  prefer those pre-computed values — they are flat and accurate.
  Example fields: Total_ExTax, Materials_Cost_Actual, Labour_Cost_Actual,
  Overhead_Cost_Actual, Gross_Profit_Actual, Gross_Margin_Pct_Actual,
  Net_Profit_Actual, Net_Margin_Pct_Actual, Budget_Status.
- NEVER invent, round, or guess dollar amounts. Copy the EXACT numbers from the payload.
- Format dollar amounts with 2 decimal places and $ sign (e.g. $10,629.80).
- If a value is 0, say so — do not omit it or invent a non-zero figure.
"""


def _get_summary_sys() -> str:
    """Build the summary system prompt, conditional on PII filter status."""
    data_section = _DATA_MASKING_SECTION if PII_FILTER_ENABLED else _REAL_DATA_SECTION
    return (
        _PERSONALITY_SUMMARY + "\n\n"
        """You are the Output Presenter.

INPUT FORMAT:
You will receive a single JSON object in the user message. It has ONE of two shapes:

A) DRAFT MODE (key "draft" present):
  - "question": the original user question (string).
  - "draft": a conversational response already written by the assistant (string).
  - "hints": optional extra context (object).
  Your job: REWRITE the draft into a concise, business-friendly summary
  that matches YOUR ROLE and COMMUNICATION STYLE above. Preserve all
  factual content from the draft but restructure it for clarity.

B) PAYLOAD MODE (key "payload" present):
  - "question": the original user question (string).
  - "payload": the structured result from tools / APIs / agents (any JSON).
  - "hints": optional extra context (object).
  Your job: read BOTH "question" and "payload" and write a clear,
  business-friendly summary that explains what was done and what the
  result means for the user.

You must NOT assume a specific business domain. The payload may describe
anything (records, tasks, files, metrics, validation results, etc.).
Adapt your wording to whatever is actually present in the data.

RESPONSE FORMAT (VERY IMPORTANT):
- You MUST return a single JSON object of the form:
  { "summary": "<text>" }
- The value of "summary" is a single string which MAY contain:
  - 1–2 introductory sentences, and
  - Optional bullet points on separate lines.
- Do NOT include any extra top-level keys.
- Do NOT wrap the JSON in markdown or code fences.
- CRITICAL: In the summary text, use only single quotes (') for any quoted terms. NEVER use backslash-escaped quotes like \\" within the summary text.

FORMAT FOR BULLET POINTS:
- When you include bullet points, each bullet MUST be on its own line.
- You MUST insert a REAL newline character before every bullet.
- Inside the summary string, bullets must be written exactly like:
    "Intro sentence.\\n- First point\\n- Second point\\n- Third point"
- NEVER put " - " or "• " directly after a sentence on the same line.
  This is INVALID: "Intro. - Point one - Point two".
  This is VALID:   "Intro.\\n- Point one\\n- Point two".
- Use "- " for bullets (not "*" or numbering).

LENGTH AND DENSITY RULES (IMPORTANT):
- The summary MUST be concise and easy to scan.
- Usually 1–3 sentences plus up to 3–6 bullet points is enough.
- If there are MANY records (for example > 10), you MUST:
  - Focus on aggregated information (counts, totals, statuses),
  - Mention only a SMALL number of concrete examples (at most 3),
  - Then say that there are "more invoices/records" instead of listing all.
- NEVER list dozens of individual invoices or records one by one.
  For example, prefer:
    "40 invoices were created, 36 succeeded and 4 failed..."
  over listing every invoice ID.
"""
        + data_section +
        """
CONTENT RULES:
- Use ONLY facts that are clearly present in the "payload".
- NEVER guess or hallucinate numbers, dates, names, or statuses.
- If something is unclear or missing, say so explicitly instead of inventing it.
- Make the summary directly relevant to the "question":
  - If the user asked to create, update, or delete something, describe what changed and how many items were affected.
  - If the user asked to check, validate, or analyze something, describe what was checked and the key findings.
  - If the user asked for a summary or overview, highlight the most important patterns or metrics.

WHAT TO FOCUS ON (adapt to the actual data you see):
1) Overall outcome:
   - Did the operation succeed, partially succeed, or fail?
   - If multiple items are involved, mention counts (e.g. how many records/items succeeded or failed).

2) Important entities and identifiers:
   - Use generic wording such as "records", "items", "entries", "rows", or specific field names you see in the payload.
   - Mention key identifiers only if they are clearly present and helpful (for example IDs, names, or labels).

3) Key fields and metrics:
   - Highlight any clearly important values such as totals, counts, dates, statuses, scores, or flags.
   - If there are many fields, focus on the ones most relevant to the user's question.

4) Errors and warnings:
   - If the payload contains errors, clearly state:
     - What part failed (which items/records if identifiable).
     - The main error messages and/or codes if available.
   - If everything appears successful, say so explicitly.

STYLE GUIDELINES:
- Be concise but informative: usually 1–3 sentences plus bullet points when helpful.
- Use plain language and avoid low-level technical jargon where possible.
- Prefer concrete statements over vague ones (e.g. "5 items were processed and 2 reported validation errors"
  instead of "There might be some issues").
- Use bullet points when there are multiple distinct outcomes or categories of results.

Again, return ONLY:
{ "summary": "..." }
nothing else.
"""
    )

SCHEMA_SYS = """You are a column schema optimizer for table displays.

INPUT:
You will receive a JSON object with these keys:
- "question": the user's original question (string). Use this to decide which columns are relevant.
- "columns": a list of column names from the data.
- "sub_tables": (optional) a list of names of nested sub-tables extracted from the data.

YOUR TASK:
Analyze the column names IN THE CONTEXT OF the user's question.
Columns that are clearly irrelevant to what the user asked should be hidden.
Columns that are directly relevant should be placed first.

For example:
- If the user asks about "profitability" or "financials", prioritize cost/profit/margin fields.
  Hide unrelated metadata like custom fields, tags, HTML notes.
- If the user asks about "job details" or "overview", keep general job info visible.
- If the user asks about "schedule" or "dates", prioritize date and time fields.
- When in doubt, keep the column visible rather than hiding it.

OUTPUT FORMAT (VERY IMPORTANT):
Return exactly ONE JSON object with this structure:

{
  "column_reorder": [<list of column names in preferred order>],
  "column_labels": {<original_name>: <readable_label>, ...},
  "hide_columns": [<list of column names to hide>],
  "hide_sub_tables": [<list of sub-table names to hide entirely>]
}

RULES:
1. column_reorder: Put the columns most relevant to the user's question first.
   Then other useful business columns. Technical/internal columns last (or hidden).
2. column_labels: Convert technical names to readable labels
   - Example: "DateIssued" → "Date Issued"
   - Example: "TotalAmount" → "Total Amount"
   - Example: "job_id" → "Job ID"
3. hide_columns: Hide columns irrelevant to the user's question.
   - Hide raw nested object counts (e.g. fields showing "5 items")
   - Hide HTML content fields, internal tags, audit trails
   - Hide duplicate or redundant information
   - Keep key identifiers and fields relevant to the question
4. hide_sub_tables: List any sub-table names that are irrelevant to the question.
   - For example, if the user asked about profitability, hide "Custom Fields" and "Tags".
   - If unsure, do NOT include the sub-table in this list (keep it visible).

Do NOT wrap in markdown or code fences. Return pure JSON only.
"""


def _llm_summary(question: str, payload: Any, hints: Dict[str, Any], llm_fn: Optional[Callable] = None) -> Optional[str]:
    """
    Generate a business-friendly summary using the shared LLM gateway.
    PII is stripped from the payload before it reaches the LLM.

    When ``hints["llm_draft"]`` is present the LLM already produced a
    conversational answer during streaming.  We pass that draft (instead
    of the heavy JSON payload) so the LLM only needs to *rewrite* it
    with the personality voice rules — much faster and cheaper.
    """
    try:
        draft: Optional[str] = (hints or {}).get("llm_draft")

        if draft:
            # ── DRAFT PATH: rewrite the streamed response with personality ──
            safe_payload = sanitize_for_llm(payload)
            record_count = None
            if isinstance(safe_payload, list):
                record_count = len(safe_payload)
            elif isinstance(safe_payload, dict):
                dk = _find_data_array(safe_payload)
                if dk:
                    record_count = len(safe_payload[dk])

            user_obj: dict = {
                "question": question,
                "draft": draft,
                "hints": {k: v for k, v in (hints or {}).items() if k != "llm_draft"},
            }
            if record_count is not None:
                user_obj["record_count"] = record_count
                user_obj["IMPORTANT"] = (
                    f"The payload contains exactly {record_count} record(s). "
                    f"Your summary MUST acknowledge these {record_count} record(s). "
                    f"Do NOT say 'no records found' or 'none found' if record_count > 0."
                )
            user = json.dumps(user_obj, ensure_ascii=False, default=str)
            print(f"[presenter] DRAFT PATH — rewriting {len(draft)} char draft with personality")
        else:
            # ── FULL PATH: summarise from raw payload ──
            safe_payload = sanitize_for_llm(payload)

            record_count = None
            _data_key = None
            if isinstance(safe_payload, list):
                record_count = len(safe_payload)
            elif isinstance(safe_payload, dict):
                _data_key = _find_data_array(safe_payload)
                if _data_key:
                    record_count = len(safe_payload[_data_key])

            sample = safe_payload
            if isinstance(safe_payload, list) and len(safe_payload) > 120:
                sample = safe_payload[:60] + safe_payload[-60:]
            elif _data_key and record_count and record_count > 120:
                sample = {**safe_payload, _data_key: safe_payload[_data_key][:60] + safe_payload[_data_key][-60:]}

            user_obj = {"question": question, "payload": sample, "hints": hints or {}}
            if record_count is not None:
                user_obj["record_count"] = record_count
                user_obj["IMPORTANT"] = (
                    f"The payload contains exactly {record_count} record(s). "
                    f"Your summary MUST acknowledge these {record_count} record(s). "
                    f"Do NOT say 'no records found' or 'none found' if record_count > 0."
                )
            user = json.dumps(user_obj, ensure_ascii=False, default=str)

        data = _llm_json(_get_summary_sys(), user, temperature=_PERSONALITY_TEMP, llm_fn=llm_fn)
        if not data:
            print("[presenter][llm][summary] _llm_json returned None")
            return None

        s = data.get("summary")
        if not isinstance(s, str):
            print("[presenter][llm][summary] 'summary' key missing or not a string:", data)
            return None

        s_clean = s.strip()
        if not s_clean:
            print("[presenter][llm][summary] summary string is empty/whitespace")
            return None
        return s_clean

    except Exception as e:
        print("[presenter][llm][summary][error]", str(e))
        return None


_schema_hints_cache: Dict[str, Dict[str, Any]] = {}
_SCHEMA_CACHE_MAX = 200  # max entries before clearing oldest half


def _llm_schema_hints(columns: List[str], question: str = "",
                      sub_table_names: Optional[List[str]] = None,
                      llm_fn: Optional[Callable] = None) -> Dict[str, Any]:
    """
    Ask the LLM about column layout.  Only column NAMES and the user's
    question are sent — no row data, no financial values.

    Results are cached by (sorted columns, sub_table_names) — the same
    column set always gets the same layout hints regardless of question.
    """
    # Build cache key from column set + sub-tables (question excluded on purpose:
    # column layout is determined by schema, not by the specific question).
    cache_key = "|".join(sorted(columns))
    if sub_table_names:
        cache_key += "||" + "|".join(sorted(sub_table_names))

    cached = _schema_hints_cache.get(cache_key)
    if cached is not None:
        print(f"[presenter][schema] Cache HIT ({len(_schema_hints_cache)} entries)")
        return cached

    try:
        payload: Dict[str, Any] = {"question": question, "columns": columns}
        if sub_table_names:
            payload["sub_tables"] = sub_table_names
        user = json.dumps(payload, ensure_ascii=False)
        data = _llm_json(SCHEMA_SYS, user, llm_fn=llm_fn) or {}
        result = {
            "column_reorder":  data.get("column_reorder") or [],
            "column_labels":   data.get("column_labels") or {},
            "hide_columns":    data.get("hide_columns") or [],
            "hide_sub_tables": data.get("hide_sub_tables") or []
        }

        # Evict oldest half when cache is full
        if len(_schema_hints_cache) >= _SCHEMA_CACHE_MAX:
            keys = list(_schema_hints_cache.keys())
            for k in keys[:len(keys) // 2]:
                _schema_hints_cache.pop(k, None)

        _schema_hints_cache[cache_key] = result
        print(f"[presenter][schema] Cache MISS → stored ({len(_schema_hints_cache)} entries)")
        return result
    except Exception as e:
        print("[presenter][llm][schema][error]", str(e))
        return {"column_reorder": [], "column_labels": {}, "hide_columns": [],
                "hide_sub_tables": []}


# ===================== Apply schema hints safely =====================
def _apply_schema_hints(columns: List[str],
                        rows: List[Dict[str, Any]],
                        hints: Dict[str, Any]) -> Tuple[List[Dict[str,str]], List[Dict[str,Any]], Dict[str, Any]]:
    existing = set(columns)
    dropped = {"reorder_not_found": [], "labels_not_found": [], "hide_not_found": []}

    reorder = [c for c in hints.get("column_reorder", []) if c in existing]
    rest = [c for c in columns if c not in reorder]
    ordered = reorder + rest

    hide = [c for c in hints.get("hide_columns", []) if c in existing]
    hidden = set(hide)
    visible = [c for c in ordered if c not in hidden]

    labels_src = hints.get("column_labels", {}) or {}
    labels: Dict[str, str] = {}
    for k, v in labels_src.items():
        if k in existing and isinstance(v, str) and v.strip():
            labels[k] = v.strip()
        else:
            dropped["labels_not_found"].append(k)

    for c in hints.get("column_reorder", []):
        if c not in existing: dropped["reorder_not_found"].append(c)
    for c in hints.get("hide_columns", []):
        if c not in existing: dropped["hide_not_found"].append(c)

    _stats_inc("dropped_keys_total", sum(len(v) for v in dropped.values()))

    cols_spec = [{"key": c, "label": labels.get(c, c)} for c in visible]
    applied = any([reorder, hide, labels])
    if applied:
        _stats_inc("hints_applied")
    else:
        _stats_inc("hints_ignored")

    return cols_spec, rows, {"applied": applied, "dropped": dropped}

# ===================== Envelopes =====================
def _fallback_summary(payload: Any) -> str:
    if isinstance(payload, list): return f"{len(payload)} records."
    if isinstance(payload, dict):
        # Auto-detect dict-wrapped arrays
        data_key = _find_data_array(payload)
        if data_key:
            return f"{len(payload[data_key])} records."
        nm = payload.get("CompanyName") or payload.get("Name") or ""
        amt = payload.get("AmountOwing") or payload.get("balance")
        bits = []
        if nm: bits.append(str(nm).strip())
        if amt is not None: bits.append(f"Owes {amt}")
        return " • ".join(bits) if bits else "1 record."
    return "Response."

def _humanize_label(key: str) -> str:
    """Turn 'CostCentre_SomeThing' into 'Cost Centre Some Thing'."""
    # Split on underscores first
    parts = key.split("_")
    # Then split camelCase within each part
    expanded = []
    for part in parts:
        expanded.append(re.sub(r'(?<=[a-z])(?=[A-Z])', ' ', part))
    return " ".join(expanded).strip()


def _build_sub_table_block(label: str, items: List[Dict[str, Any]]) -> Dict[str, Any]:
    """Build a table block for a nested array (e.g. CostCentres)."""
    sub_rows: List[Dict[str, Any]] = []
    for item in items:
        flat, _ = _flatten_row(item)          # flatten one level (ignore deeper nesting)
        sub_rows.append(flat)

    sub_cols: List[str] = []
    seen = set()
    for r in sub_rows:
        for k in r.keys():
            if k not in seen:
                seen.add(k); sub_cols.append(k)

    cols_spec = [{"key": c, "label": _humanize_label(c)} for c in sub_cols]
    shown = min(UI_PREVIEW_ROWS, len(sub_rows))

    return {
        "type": "table",
        "title": _humanize_label(label),
        "spec": {
            "columns": cols_spec,
            "rows": sub_rows[:shown],
            "preview": {"shown": shown, "total": len(sub_rows)},
            "downloads": [
                {"type": "csv", "blob": _csv_blob_full(sub_rows)},
                {"type": "json", "blob": "data:application/json," + quote(json.dumps(items, default=str))},
                {"type": "xlsx", "blob": _xlsx_blob(sub_rows)},
            ],
            "note": (f"Showing {shown} of {len(sub_rows)}." if len(sub_rows) > shown else None),
        },
    }


def _envelope_from_rows(rows: List[Dict[str, Any]], summary: str, original_payload: Any,
                        enable_hints: bool,
                        all_nested: Optional[Dict[str, List]] = None,
                        question: str = "",
                        precomputed_hints: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
    cols: List[str] = []
    seen = set()
    for r in rows:
        for k in r.keys():
            if k not in seen:
                seen.add(k); cols.append(k)

    shown = min(UI_PREVIEW_ROWS, len(rows))

    sub_table_names = list(all_nested.keys()) if all_nested else []

    if precomputed_hints is not None:
        # Use pre-fetched hints (from parallel execution in present())
        _stats_inc("hints_requested")
        cols_spec, rows_final, tele = _apply_schema_hints(cols, rows, precomputed_hints)
        hidden_subs = set(precomputed_hints.get("hide_sub_tables") or [])
    elif enable_hints and rows:
        _stats_inc("hints_requested")
        hints = _llm_schema_hints(cols, question=question,
                                  sub_table_names=sub_table_names or None)
        cols_spec, rows_final, tele = _apply_schema_hints(cols, rows, hints)
        hidden_subs = set(hints.get("hide_sub_tables") or [])
    else:
        cols_spec = [{"key": c, "label": _humanize_label(c)} for c in cols]
        rows_final = rows
        tele = {"applied": False, "dropped": {}}
        hidden_subs = set()

    _stats_inc("columns_built_total", len(cols_spec))

    main_block = {
        "type": "table",
        "title": "Results" if len(rows) > 1 else "Record",
        "spec": {
            "columns": cols_spec,
            "rows": rows_final[:shown],
            "preview": {"shown": shown, "total": len(rows_final)},
            "downloads": [
                {"type":"csv","blob": _csv_blob_full(rows_final)},
                {"type":"json","blob":"data:application/json," + quote(json.dumps(original_payload, default=str))},
                {"type":"xlsx","blob": _xlsx_blob(rows_final)}
            ],
            "note": (f"Showing {shown} of {len(rows_final)}. Download CSV/Excel for all rows."
                     if len(rows_final) > shown else None)
        },
        "telemetry": tele
    }

    blocks = [main_block]

    # Add sub-table blocks, skipping any the LLM marked as irrelevant
    if all_nested:
        for key, items in all_nested.items():
            if items and key not in hidden_subs:
                blocks.append(_build_sub_table_block(key, items))

    env = {
        "title": "Results",
        "summary": summary,
        "blocks": blocks,
    }
    return env

# ===================== Route =====================
@router.post("/present", response_model=PresentResponse)
def present(req: PresentRequest):
    payload = req.payload
    hints = req.hints or {}
    llm_fn = req.llm_fn or None  # Per-org LLM fn from chat.py; None → falls back to global llm_chat

    # Log incoming payload
    try:
        safe_log = sanitize_for_llm(payload)
        print("\n\n=== PAYLOAD FROM AGENT (PII-safe) ===")
        print(json.dumps(safe_log, ensure_ascii=False, indent=2, default=str)[:3000])
        print("=== END PAYLOAD ===\n\n")
    except Exception as e:
        print("[presenter][payload_in][error_serializing]", str(e))

    try:
        # 1) Build table rows LOCALLY — no LLM, no data leak
        rows, _, all_nested = _flatten_top_level(payload)

        # 2) Determine schema hints toggle
        enable_hints = hints.get("llm_schema_hints")
        if enable_hints is None:
            enable_hints = PRESENTER_USE_LLM_SCHEMA_HINTS

        # 3) LLM calls — parallel when both summary + schema hints are needed
        #    llm_draft (if present in hints) lets _llm_summary() rewrite the
        #    streamed text with personality instead of analysing raw JSON.
        if enable_hints and rows:
            from concurrent.futures import ThreadPoolExecutor
            cols = [c for c in rows[0].keys()] if rows else []
            sub_table_names = list(all_nested.keys()) if all_nested else []
            with ThreadPoolExecutor(max_workers=2) as pool:
                summary_future = pool.submit(_llm_summary, req.question, payload, hints, llm_fn)
                hints_future = pool.submit(_llm_schema_hints, cols, req.question, sub_table_names or None, llm_fn)
                summary = summary_future.result() or _fallback_summary(payload)
                schema_hints = hints_future.result()
            env = _envelope_from_rows(rows, summary, payload, False, all_nested,
                                      question=req.question, precomputed_hints=schema_hints)
        else:
            summary = _llm_summary(req.question, payload, hints, llm_fn) or _fallback_summary(payload)
            env = _envelope_from_rows(rows, summary, payload, False, all_nested,
                                      question=req.question)

        # 5) Telemetry + logging
        _telemetry_log("render", {
            "enable_hints": bool(enable_hints),
            "rows": len(rows),
            "cols": len(env["blocks"][0]["spec"]["columns"]),
            "llm_provider": LLM_PROVIDER,
            "llm_model": LLM_MODEL,
        })
        print("[presenter][summary]", (summary or "").strip()[:200])

        return PresentResponse(envelope=env, telemetry={
            "model": f"{LLM_PROVIDER}:{LLM_MODEL}",
            "env_llm_schema_hints": PRESENTER_USE_LLM_SCHEMA_HINTS
        })

    except Exception as e:
        _telemetry_log("error", {"error": str(e)})
        fallback = {
            "summary": "Response.",
            "blocks": [{
                "type": "json",
                "title": "Raw JSON",
                "spec": {
                    "json": payload,
                    "downloads": [{
                        "type": "json",
                        "blob": "data:application/json," + quote(json.dumps(payload, default=str))
                    }]
                }
            }]
        }
        return PresentResponse(
            envelope=fallback,
            telemetry={"error": str(e), "fallback": True, "model": f"{LLM_PROVIDER}:{LLM_MODEL}"}
        )
